trigger:
  - main  # Runs on every push to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Fetches code from GitHub

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js 20.x'

  - script: |
      npm install
      npm run build
    displayName: "Install dependencies and build React app"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
    displayName: "Archive build artifacts"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: "Publish build artifacts"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'YourAzureServiceConnection'
      appName: 'your-react-webapp'
      package: '$(Build.ArtifactStagingDirectory)/build.zip'
    displayName: "Deploy to Azure Web App"
